### ISSUE TITLE
Dropdown not displaying properly. 

### ISSUE THREAD

**Issue by romans127** [jshimko/meteor-autoform-selectize#4]
I have created my selectize attribute as instructed in the docs however the form displays like so . 

http://screencast.com/t/fB8yWzauiy . 

Any advice will be greatly appreciated.

**Comment by jshimko** [comment]
Looks like you may have some CSS conflicts.  If you have a public repo I can look at, I'd be happy to take a look to confirm.

**Comment by KristerV** [comment]
i fixed this issue by adding `chhib:selectize-bootstrap-3`
